# Generated by Django 5.1.1 on 2024-10-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('event_date', models.DateField()),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Event',
            },
        ),
    ]
