# Generated by Django 5.1.1 on 2024-11-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_event_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
